version: 2.1
jobs:
  build:
    working_directory: ~/docker-react
    docker:
      - image: circleci/node:
    steps:
      - checkout
    - run:
        name: install-npm-wee
        command: npm install
    - save_cache: # special step to save the dependency cache
        key: dependency-cache-{{ checksum "yarn.lock" }}
        paths:
          - ./node_modules
    - run: # run tests
        name: test
        command: npm test
    - run: # run coverage report
        name: code-coverage
        command: './node_modules/.bin/nyc report --reporter=text-lcov'
    - store_artifacts: # special step to save test results as as artifact
        # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
        path: test-results.xml
        prefix: tests
    - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
        path: coverage
        prefix: coverage
    - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
        path: test-results.xml
    # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
